# Site settings
title: Stojan Anastasov's blog
description: 'Android developer crafting native Android apps'
url: 'http://lordraydenmk.github.io/'
baseurl: ''
google_analytics: 'UA-42931201-6'
disqus_shortname: 'lordraydenmk'

author:
  name: 'Stojan Anastasov'
  email: stolea@gmail.com
  github_username:  lordraydenmk
  linkedin_username:  sanastasov
  bluesky_username: sanastasov.com
  twitter_username: s_anastasov
  stackoverflow: 1011435/lordraydenmk

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'vendor']
